version: '3.8'


services:

  api-test_app:
    build: .
    image: "api-test_app"
    volumes:
      - .:/api_test_app
      - allure_results:/api_test_app/allure-results


  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 5
    ports:
      - "5050:5050"
    volumes:
      - allure_results:/app/allure-results


  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

volumes:
  allure_results:
